### ISSUE TITLE
1.4 - [BUG] [WEB] CORREÇÃO DA TELA DE PARCEIROS

### ISSUE THREAD

**Issue by daniellsfilho** [ProManage-FatecSJC/pro-manager-web#23]
Corrigir tela de parceiros do sistema web, a qual está apresentando problemas na estrutura ao exibir vários usuários.

Sugestão:
Reestruturar o html ou o scss, acho que tentar achar o que tá dando problema vai dar muito trabalho

**Comment by vbuarque** [comment]
Tarefa começado dia 27/04 ás 20:00

**Comment by vbuarque** [comment]
Tarefa finalizada dia 27/04 ás 23:25

Aguardando para realizar testes.

**Comment by vbuarque** [comment]
Testes finalizados, ok
