### ISSUE TITLE
Filtros de Pesquisa (Front-end)

### ISSUE THREAD

**Issue by bruno-pisciotta281** [ProManage-FatecSJC/pro-manager-web#8]
Filtros de pesquisa aonde irá separar os parceiros listados em data de criação, ordem alfabética (Data de criação, ordem alfabética, separado por parceiro).

Peso: 5

**Comment by vbuarque** [comment]
Task começada dia 20/03
(Front-end finalizado só falta finalizar a lógica dos filtros)
